### ISSUE TITLE
东东萌宠运行错误

### ISSUE THREAD

**Issue by anakinlee99** [wuzhi03/MyActions#56]
昨天开始，东东萌宠老是运行错误，错误代码如下。
大佬帮忙看一下。

东东萌宠: API查询请求失败 ‼️‼️
"connect ETIMEDOUT 116.198.168.64:443"

❗️东东萌宠, 错误!

❗️东东萌宠, 错误!
TypeError: Cannot read property 'code' of undefined
    at slaveHelp (/jd/scripts/jd_pet.js:286:18)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async jdPet (/jd/scripts/jd_pet.js:132:7)
    at async /jd/scripts/jd_pet.js:72:7

**Comment by wuzhi03** [comment]
某个值获取失败，重新运行几次吧
